# matrix_analytics.py
import os
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

CSV_FILENAME = "coffee_adaptation_matrix.csv"

# Thesis color palette for the key producers
PRODUCER_COLORS = {
    'Brazil': '#1f77b4',     # Blue
    'Vietnam': '#ff7f0e',    # Orange
    'Colombia': '#2ca02c',   # Green
    'Ethiopia': '#d62728',   # Red
    'Honduras': '#9467bd',   # Purple
    'Peru': '#8c564b',       # Brown
    'Mexico': '#e377c2',     # Pink
    'Guatemala': '#7f7f7f',  # Grey
    'Nicaragua': '#bcbd22',  # Olive
    'Indonesia': '#17becf'   # Cyan
}

@st.cache_data
def load_matrix_csv():
    """
    Loads country adaptation metrics directly from the CSV generated by the notebook.
    No numbers are hardcoded.
    """
    if not os.path.exists(CSV_FILENAME):
        return None
    df = pd.read_csv(CSV_FILENAME)
    return df


def render_dynamic_comparative_advantage_matrix():
    """
    Renders the thesis Figure 7 matrix directly from the exported CSV dataset
    using CARS/BLADE communication principles.
    """
    df_raw = load_matrix_csv()

    if df_raw is None:
        st.error(
            f"File `{CSV_FILENAME}` not found. "
            "Please run Cell 20 in `Code_Python.ipynb` with `final_stats.to_csv('coffee_adaptation_matrix.csv')` "
            "and place the CSV in the same folder as `coffee_app.py`."
        )
        return

    # Extract dynamic country list from the CSV
    available_countries = sorted(df_raw['country'].unique().tolist())
    
    # Show every country available in the export by default.
    selected_countries = st.multiselect(
        "Select Countries to Display on Adaptation Matrix:",
        options=available_countries,
        default=available_countries,
        help="Add or remove producer nations dynamically from the CSV dataset."
    )

    if not selected_countries:
        st.info("Please select at least one country to display on the matrix.")
        return

    # Filter dataframe to user selection
    df = df_raw[df_raw['country'].isin(selected_countries)].copy()

    # Dynamic scaling based on maximum viable footprint in current view
    max_area = df['total_viable_ha'].max()
    if pd.isna(max_area) or max_area <= 0:
        max_area = 1.0

    # Build Plotly Figure
    fig = go.Figure()

    for _, row in df.iterrows():
        c_name = row['country']
        
        # Color accentuation
        bubble_color = PRODUCER_COLORS.get(
            c_name, 
            '#2b8cbe' if str(row.get('region')) == 'Americas' else (
                '#31a354' if str(row.get('region')) == 'Africa' else '#ff7f0e'
            )
        )

        fig.add_trace(go.Scatter(
            x=[row['avg_lcow']],
            y=[row['deficit_per_ha']],
            mode="markers+text",
            name=c_name,
            text=[c_name],
            textposition="top center",
            textfont=dict(size=12, family="Arial", color="#ffffff"),
            marker=dict(
                size=[row['total_viable_ha']],
                sizemode="area",
                sizeref=2.0 * max_area / (55.0 ** 2),
                sizemin=10,
                color=bubble_color,
                opacity=0.88,
                line=dict(width=1.5, color="#ffffff")
            ),
            hovertemplate=(
                f"<b>{c_name}</b><br>" +
                "Avg Irrigation Cost: <b>$%{x:.2f}/m³</b><br>" +
                "Avg Irrigation Demand: <b>%{y:.1f} m³/viable ha</b><br>" +
                f"Total Viable Footprint: <b>{row.get('area_mha', round(row['total_viable_ha']/1e6, 1))}M ha</b>" +
                "<extra></extra>"
            ),
            showlegend=True
        ))

    # BLADE: Delineate Median/Threshold Benchmarks
    fig.add_vline(x=0.75, line_width=1.2, line_dash="dash", line_color="#555555")
    fig.add_hline(y=350, line_width=1.2, line_dash="dash", line_color="#555555")

    # BLADE: Label Quadrants
    fig.add_annotation(
        x=0.35, y=950,
        text="<b>CAPITAL-INTENSIVE INCUMBENTS</b><br>High Demand, Low Cost Delivery (Brazil)",
        showarrow=False, font=dict(size=11, color="#88bde6"), align="left"
    )
    fig.add_annotation(
        x=0.35, y=50,
        text="<b>PROTECTED COMPETITIVE CORE</b><br>Low Demand, Affordable Delivery (Colombia)",
        showarrow=False, font=dict(size=11, color="#a1d99b"), align="left"
    )
    fig.add_annotation(
        x=1.45, y=950,
        text="<b>EXTREME MALADAPTATION RISK</b><br>High Demand, Prohibitive Infrastructure",
        showarrow=False, font=dict(size=11, color="#fdae6b"), align="left"
    )
    fig.add_annotation(
        x=1.45, y=50,
        text="<b>CAPITAL-CONSTRAINED RISK</b><br>Low Demand, High Cost Multipliers (Indonesia, Peru)",
        showarrow=False, font=dict(size=11, color="#fdae6b"), align="left"
    )

    # Dynamic Axis Bounds matching Thesis Figure 7
    x_max = max(float(df['avg_lcow'].max()) * 1.15, 2.05)
    y_max = max(float(df['deficit_per_ha'].max()) * 1.25, 1050.0)

    # CARS Layout Styling
    fig.update_layout(
        title={
            "text": "<b>Global Comparative Advantage Matrix (The Adaptation Premium)</b><br>" +
                    "<span style='font-size:12px; color:#cccccc;'>Data source: coffee_adaptation_matrix.csv (Notebook Cell 20).</span>",
            "x": 0.02,
            "xanchor": "left"
        },
        xaxis=dict(
            title="<b>Average Irrigation Cost ($/m³)</b>",
            range=[0.0, x_max],
            dtick=0.25,
            gridcolor="#2c2f36",
            zeroline=False
        ),
        yaxis=dict(
            title="<b>Average Irrigation Demand (m³ / viable hectare)</b>",
            range=[0, y_max],
            dtick=200,
            gridcolor="#2c2f36",
            zeroline=False
        ),
        plot_bgcolor="#18191c",
        paper_bgcolor="#0e1117",
        legend=dict(
            title=dict(text="<b>Producer</b>", font=dict(size=11, color="#ffffff")),
            orientation="v",
            yanchor="top",
            y=1.0,
            xanchor="left",
            x=1.02,
            font=dict(color="#ffffff")
        ),
        margin=dict(l=50, r=160, t=90, b=50),
        height=620
    )

    st.plotly_chart(fig, use_container_width=True)