# matrix_analytics.py
import os
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

CSV_FILENAME = "coffee_adaptation_matrix.csv"
CSV_PATH = os.path.join(os.path.dirname(__file__), CSV_FILENAME)

# Thesis color palette for the key producers
PRODUCER_COLORS = {
    'Brazil': '#1f77b4',     # Blue
    'Vietnam': '#ff7f0e',    # Orange
    'Colombia': '#2ca02c',   # Green
    'Ethiopia': '#d62728',   # Red
    'Honduras': '#9467bd',   # Purple
    'Peru': '#8c564b',       # Brown
    'Mexico': '#e377c2',     # Pink
    'Guatemala': '#7f7f7f',  # Grey
    'Nicaragua': '#bcbd22',  # Olive
    'Indonesia': '#17becf'   # Cyan
}

DEFAULT_COUNTRIES = [
    'Brazil', 'Vietnam', 'Colombia', 'Ethiopia', 'Honduras',
    'Peru', 'Mexico', 'Guatemala', 'Nicaragua', 'Indonesia'
]

@st.cache_data
def load_matrix_csv(modified_at):
    """
    Loads country adaptation metrics directly from the CSV generated by the notebook.
    No numbers are hardcoded.
    """
    if not os.path.exists(CSV_PATH):
        return None
    df = pd.read_csv(CSV_PATH)
    return df


def render_dynamic_comparative_advantage_matrix():
    """
    Renders the thesis Figure 7 matrix directly from the exported CSV dataset
    using CARS/BLADE communication principles.
    """
    modified_at = os.path.getmtime(CSV_PATH) if os.path.exists(CSV_PATH) else None
    df_raw = load_matrix_csv(modified_at)

    if df_raw is None:
        st.error(
            f"File `{CSV_FILENAME}` not found. "
            "Please run Cell 20 in `Code_Python.ipynb` with `final_stats.to_csv('coffee_adaptation_matrix.csv')` "
            "and place the CSV in the same folder as `coffee_app.py`."
        )
        return

    # Extract dynamic country list from the CSV
    available_countries = sorted(df_raw['country'].unique().tolist())
    
    # Start with the original producer set, while leaving all CSV countries selectable.
    default_selection = [country for country in DEFAULT_COUNTRIES if country in available_countries]
    if not default_selection:
        default_selection = available_countries[:10]

    selected_countries = st.multiselect(
        "Select Countries to Display on Adaptation Matrix:",
        options=available_countries,
        default=default_selection,
        key="matrix_country_selection_top10_default",
        help="Add or remove producer nations dynamically from the CSV dataset."
    )

    if not selected_countries:
        st.info("Please select at least one country to display on the matrix.")
        return

    # Filter dataframe to user selection
    df = df_raw[df_raw['country'].isin(selected_countries)].copy()
    df = df.replace([float('inf'), float('-inf')], pd.NA)
    df = df.dropna(subset=['avg_lcow', 'deficit_per_ha', 'total_viable_ha'])

    if df.empty:
        st.warning("The selected countries do not have valid cost, demand, and footprint data.")
        return

    # Dynamic scaling based on maximum viable footprint in current view
    max_area = df['total_viable_ha'].max()
    if pd.isna(max_area) or max_area <= 0:
        max_area = 1.0

    # Build Plotly Figure
    fig = go.Figure()

    for _, row in df.iterrows():
        c_name = row['country']
        
        # Color accentuation
        bubble_color = PRODUCER_COLORS.get(
            c_name, 
            '#2b8cbe' if str(row.get('region')) == 'Americas' else (
                '#31a354' if str(row.get('region')) == 'Africa' else '#ff7f0e'
            )
        )

        fig.add_trace(go.Scatter(
            x=[row['avg_lcow']],
            y=[row['deficit_per_ha']],
            mode="markers+text",
            name=c_name,
            text=[c_name],
            textposition="top center",
            textfont=dict(size=12, family="Arial", color="#ffffff"),
            marker=dict(
                size=[row['total_viable_ha']],
                sizemode="area",
                sizeref=2.0 * max_area / (55.0 ** 2),
                sizemin=10,
                color=bubble_color,
                opacity=0.88,
                line=dict(width=1.5, color="#ffffff")
            ),
            hovertemplate=(
                f"<b>{c_name}</b><br>" +
                "Avg Irrigation Cost: <b>$%{x:.2f}/m³</b><br>" +
                "Avg Irrigation Demand: <b>%{y:.1f} m³/viable ha</b><br>" +
                f"Total Viable Footprint: <b>{row.get('area_mha', round(row['total_viable_ha']/1e6, 1))}M ha</b>" +
                "<extra></extra>"
            ),
            showlegend=True
        ))

    # Recalculate the reference split from the currently selected countries.
    x_mid = float(df['avg_lcow'].median())
    y_mid = float(df['deficit_per_ha'].median())
    fig.add_vline(x=x_mid, line_width=1.2, line_dash="dash", line_color="#8a8f98")
    fig.add_hline(y=y_mid, line_width=1.2, line_dash="dash", line_color="#8a8f98")

    # Keep short quadrant labels in the corners, independent of the data scale.
    fig.add_annotation(
        x=0.02, y=0.98, xref="paper", yref="paper", xanchor="left", yanchor="top",
        text="<b>HIGHER DEMAND · LOWER COST</b>", showarrow=False,
        font=dict(size=10, color="#88bde6"), align="left",
        bgcolor="rgba(24,25,28,0.82)", borderpad=3
    )
    fig.add_annotation(
        x=0.02, y=0.02, xref="paper", yref="paper", xanchor="left", yanchor="bottom",
        text="<b>LOWER DEMAND · LOWER COST</b>", showarrow=False,
        font=dict(size=10, color="#a1d99b"), align="left",
        bgcolor="rgba(24,25,28,0.82)", borderpad=3
    )
    fig.add_annotation(
        x=0.98, y=0.98, xref="paper", yref="paper", xanchor="right", yanchor="top",
        text="<b>HIGHER DEMAND · HIGHER COST</b>", showarrow=False,
        font=dict(size=10, color="#fdae6b"), align="right",
        bgcolor="rgba(24,25,28,0.82)", borderpad=3
    )
    fig.add_annotation(
        x=0.98, y=0.02, xref="paper", yref="paper", xanchor="right", yanchor="bottom",
        text="<b>LOWER DEMAND · HIGHER COST</b>", showarrow=False,
        font=dict(size=10, color="#fdae6b"), align="right",
        bgcolor="rgba(24,25,28,0.82)", borderpad=3
    )

    # Fit axes and tick spacing to the selected values instead of fixed thesis bounds.
    x_data_max = max(float(df['avg_lcow'].max()), 0.0)
    y_data_max = max(float(df['deficit_per_ha'].max()), 0.0)
    x_max = max(x_data_max * 1.12, 0.1)
    y_max = max(y_data_max * 1.12, 1.0)

    # CARS Layout Styling
    fig.update_layout(
        title={
            "text": "<b>Global Comparative Advantage Matrix (The Adaptation Premium)</b><br>" +
                    "<span style='font-size:12px; color:#cccccc;'>Data source: coffee_adaptation_matrix.csv (Notebook Cell 20).</span>",
            "x": 0.02,
            "xanchor": "left"
        },
        xaxis=dict(
            title="<b>Average Irrigation Cost ($/m³)</b>",
            range=[0.0, x_max],
            gridcolor="#2c2f36",
            zeroline=False
        ),
        yaxis=dict(
            title="<b>Average Irrigation Demand (m³ / viable hectare)</b>",
            range=[0, y_max],
            gridcolor="#2c2f36",
            zeroline=False
        ),
        plot_bgcolor="#18191c",
        paper_bgcolor="#0e1117",
        legend=dict(
            title=dict(text="<b>Producer</b>", font=dict(size=11, color="#ffffff")),
            orientation="v",
            yanchor="top",
            y=1.0,
            xanchor="left",
            x=1.02,
            font=dict(color="#ffffff")
        ),
        margin=dict(l=50, r=160, t=90, b=50),
        height=620
    )

    st.plotly_chart(fig, width="stretch")